# /etc/doas.conf

# Usuario principal: persist (contraseña) para todo
permit persist ori as root

# Herramientas del sistema: sin contraseña
permit nopass ori as root cmd pacman
permit nopass ori as root cmd paru
permit nopass ori as root cmd systemctl
permit nopass ori as root cmd journalctl
permit nopass ori as root cmd reboot
permit nopass ori as root cmd shutdown

# Seguridad: denegar todo lo demas
deny all
